version: "3.8"

services:
  freelance_bot:
    build: .
    container_name: freelance_lena_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8001:8000"
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
